name: Copy API_KEY1 to API_KEY2
on:
  workflow_dispatch:

jobs:
  copy-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Copy secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SOURCE_VALUE: ${{ secrets.API_KEY1 }}
        run: |
          echo "::add-mask::$SOURCE_VALUE"
          gh secret set API_KEY2 --body "$SOURCE_VALUE"
